# Generated by Django 5.2 on 2026-02-22 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_image'),
        ('orders', '0003_order_comment_order_delivery_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(blank=True, help_text='Пусто = использовать общий порог из настроек сайта.', null=True, verbose_name='Порог «мало на складе»'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(verbose_name='Остаток на складе'),
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Положительное — приход, отрицательное — списание.', verbose_name='Количество')),
                ('movement_type', models.CharField(choices=[('receipt', 'Приход'), ('write_off', 'Списание'), ('adjustment', 'Корректировка'), ('order', 'Заказ')], default='adjustment', max_length=20, verbose_name='Тип')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='orders.order', verbose_name='Заказ (если списание по заказу)')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='catalog.product')),
            ],
            options={
                'verbose_name': 'Движение по складу',
                'verbose_name_plural': 'Движения по складу',
                'ordering': ['-created_at'],
            },
        ),
    ]
