# Generated by Django 5.2 on 2026-02-20 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(choices=[('about', 'О нас'), ('delivery', 'Доставка'), ('contacts', 'Контакты'), ('faq', 'Вопросы и ответы'), ('warranty', 'Гарантия'), ('how_to_order', 'Как заказать'), ('wholesale', 'Оптовикам'), ('pickup', 'Самовывоз'), ('support', 'Техподдержка'), ('other', 'Другое')], unique=True, verbose_name='Код страницы')),
                ('content', models.TextField(verbose_name='Содержимое (HTML или текст)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Показывать на сайте')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Страница',
                'verbose_name_plural': 'Страницы',
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Автокраска', max_length=200, verbose_name='Название сайта')),
                ('contact_phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('contact_address', models.TextField(blank=True, verbose_name='Адрес')),
                ('delivery_info', models.TextField(blank=True, verbose_name='Информация о доставке')),
                ('payment_info', models.TextField(blank=True, verbose_name='Информация об оплате')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
    ]
