# Generated by Django 5.2 on 2026-02-22 15:26

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_page_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('slug', models.SlugField(choices=[('order_confirmation', 'Подтверждение заказа'), ('order_status', 'Изменение статуса заказа'), ('password_reset', 'Сброс пароля'), ('welcome', 'Приветственное письмо'), ('other', 'Другое')], unique=True, verbose_name='Код')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема письма')),
                ('body', models.TextField(help_text='Переменные: {{ order_id }}, {{ user_name }}, {{ site_name }} и т.д.', verbose_name='Текст письма (HTML или текст)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Использовать этот шаблон')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Шаблон письма',
                'verbose_name_plural': 'Шаблоны писем',
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='currency',
            field=models.CharField(default='BYN', help_text='Например: BYN, USD, EUR', max_length=10, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='delivery_methods',
            field=models.JSONField(blank=True, default=core.models.default_delivery_methods, help_text='Список объектов: [{"id": "courier", "name": "Курьер", "description": "по городу"}]', verbose_name='Способы доставки'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='payment_methods',
            field=models.JSONField(blank=True, default=core.models.default_payment_methods, help_text='Список объектов: [{"id": "cash", "name": "Наличными", "description": ""}]', verbose_name='Способы оплаты'),
        ),
    ]
