# Generated by Django 5.2 on 2026-02-22 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_image'),
        ('core', '0003_site_settings_currency_delivery_payment_email_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('start_date', models.DateTimeField(verbose_name='Начало')),
                ('end_date', models.DateTimeField(verbose_name='Окончание')),
                ('discount_type', models.CharField(choices=[('percent', 'Процент'), ('fixed', 'Фиксированная сумма')], default='percent', max_length=10, verbose_name='Тип скидки')),
                ('value', models.DecimalField(decimal_places=2, help_text='Процент (0-100) или сумма', max_digits=10, verbose_name='Значение')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('categories', models.ManyToManyField(blank=True, help_text='Пусто и товары пусто = на весь каталог. Иначе только выбранные категории/товары.', to='catalog.category', verbose_name='Категории')),
                ('products', models.ManyToManyField(blank=True, to='catalog.product', verbose_name='Товары')),
            ],
            options={
                'verbose_name': 'Кампания (акция по датам)',
                'verbose_name_plural': 'Кампании',
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('discount_type', models.CharField(choices=[('percent', 'Процент'), ('fixed', 'Фиксированная сумма')], default='percent', max_length=10, verbose_name='Тип скидки')),
                ('value', models.DecimalField(decimal_places=2, help_text='Процент (0-100) или сумма в валюте', max_digits=10, verbose_name='Значение')),
                ('min_order_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Пусто = без ограничения', max_digits=10, null=True, verbose_name='Минимальная сумма заказа')),
                ('valid_from', models.DateTimeField(blank=True, null=True, verbose_name='Действителен с')),
                ('valid_until', models.DateTimeField(blank=True, null=True, verbose_name='Действителен до')),
                ('max_uses', models.PositiveIntegerField(blank=True, help_text='Пусто = неограниченно', null=True, verbose_name='Макс. использований')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Использовано раз')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('categories', models.ManyToManyField(blank=True, help_text='Пусто = на все товары. Иначе скидка только на товары из этих категорий.', to='catalog.category', verbose_name='Категории')),
                ('products', models.ManyToManyField(blank=True, help_text='Пусто = по категориям или весь заказ. Иначе скидка только на эти товары.', to='catalog.product', verbose_name='Товары')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
            },
        ),
    ]
