# Generated by Django 5.2 on 2026-02-22 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_promocode_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='low_stock_threshold',
            field=models.PositiveIntegerField(default=5, help_text='Товары с остатком ниже этого значения подсвечиваются в админке. Для товара можно задать свой порог.', verbose_name='Порог «мало на складе»'),
        ),
    ]
